on: [push, pull_request]
name: flutter test
jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.9.1+hotfix.6'
      - run: flutter analyze
      - run: flutter test
